### ISSUE TITLE
Always black unless Slider is moved.

### ISSUE THREAD

**Issue by Siriss** [hayashi311/Color-Picker-for-iOS#23]
The HRColorPickerView always returns black. When I move the slider I can see it is purple, but the brightness is always set to 0 on init. I have set it up just like the example project.

**Comment by cliffjoyce** [comment]
I've found that this happens when HRColorPickerView.tileSize is 1.  When tileSize is > 1, then the HRBrightnessSlider indeed properly changes HRColorPickerView's opacity as it should.  I've looked through the code, and have not found a way to fix this myself.

**Comment by jabels** [comment]
@Siriss Believe I was getting the same issue as you. Within Storyboard, the View that contains the 3 controls (in the sample the hierarchy is View Controller > View > Color Picker View), under identity inspector, do you have a runtime attribute set for 'color' with type of Color like the sample project does?

**Comment by ryanmay** [comment]
@cliffjoyce @jabels @Siriss  I can confirm that setting the 'color' runtime attribute will fix the initial black color problem by adding the attribute to the HRColorPickerView

![screen shot 2015-06-24 at 10 37 23 am](https://cloud.githubusercontent.com/assets/4553495/8332694/42806d6c-1a5d-11e5-858a-43566afc597a.png)

**Comment by hayashi311** [comment]
I'm sorry for the delay in fix.
I understand bug and fixed it.
