### ISSUE TITLE
Pod download not up to date

### ISSUE THREAD

**Issue by mbachrach** [hayashi311/Color-Picker-for-iOS#24]
The version I just obtained using cocoa pods has some bugs that are fixed in your current master.  For example, programmatically setting the color doesn't have any effect on the views in the pods version, but in your master branch, it has been fixed and does have the expected effect.

**Comment by pedro380085** [comment]
This project is still actively supported?

**Comment by hayashi311** [comment]
Sorry. I pushed podspec to CocoaPods today
