### ISSUE TITLE
Can't pick up white, and back color from the ColorPickerView

### ISSUE THREAD

**Issue by roman0914** [hayashi311/Color-Picker-for-iOS#25]
I like the color picker. But unfortunately, it is NOT easy to get a white color on there. Its frustrating. I can't seem to get the white color for the background. Since white & black are the main colors that users will use as the background, so I think changing color picker will be needed here. 
Do you have any recommendations ? 

Thanks.

**Comment by Peyotle** [comment]
I know this question is old, but maybe it will be helpful for someone else.
To make possible selection of the white color you should change saturationUpperLimit of HRColorMapView to 1. And to enable black - change brightnessLowerLimit of HRBrightnessSlider to 0.

**Comment by drewmccormack** [comment]
Thanks @Peyotle. That was very useful information. Don't really understand why this is not the default.
