### ISSUE TITLE
colorMapView can not show

### ISSUE THREAD

**Issue by acwind** [hayashi311/Color-Picker-for-iOS#31]
follow the step of README
colorMapView can not show
HRBrightnessSlider can show
HRColorInfoView can show

what's wrong with my step?

**Comment by hayashi311** [comment]
Did you try sample project?

**Comment by Tagalong** [comment]
Same here, followed Sample Project exactly - added colorPickerView with subviews, connected subviews in Connections Inspector to colorPickerView and made view controller exactly like SampleViewController. ColorMapView still not showing.

**Comment by amoshsueh** [comment]
You need to set up saturationUpperLimit and tileSize key paths in storyboard, otherwise the isAbleToCreateColorMap() will return FALSE and initializeQueue will not start running.
