### ISSUE TITLE
colorMapView does not follow orientation changes

### ISSUE THREAD

**Issue by skuske** [hayashi311/Color-Picker-for-iOS#33]
When changing from portrait to landscape, colorMapView remains in it's portrait layout. Any fix for that?

Thanks.

**Comment by toby-pondr** [comment]
In your HRColorMapView.m file, call `[self createColorMapLayer];` in its `layoutSubviews` method. Also update the start of your createColorMapLayer method with: `- (void)createColorMapLayer {
    if (self.colorMapLayer) {
		self.colorMapLayer.frame = (CGRect) {.origin = CGPointZero, .size = self.frame.size};
		self.colorMapBackgroundLayer.frame = (CGRect) {.origin = CGPointZero, .size = self.frame.size};
        return;
    }`
