### ISSUE TITLE
Support Xcode 12.2

### ISSUE THREAD

**Issue by behzadardehei** [hayashi311/Color-Picker-for-iOS#57]
The SPM doesn't support Xcode 12

Showing All Messages
https://github.com/hayashi311/Color-Picker-for-iOS has no Package.swift manifest for version 3.0.0

**Comment by ryh** [comment]
The author did not add new version tag after commit https://github.com/hayashi311/Color-Picker-for-iOS/commit/79a43b4f54c2e00c78ed7aa03c82bdd9e195102d yet

**Comment by hayashi311** [comment]
It works correctly now. Thank you for your report.
