### ISSUE TITLE
3.0.1 to CocoaPods repository

### ISSUE THREAD

**Issue by Igor-Palaguta** [hayashi311/Color-Picker-for-iOS#60]
Probably 3.0.1 can be pushed to cocoapods repository

If I mention in Podfile, CocoaPods cannot find version
```ruby
pod 'Colorful', '~> 3.0.1'
```

**Comment by hayashi311** [comment]
👍

**Comment by Igor-Palaguta** [comment]
Thanks, for a new tag. please can you also push new version to podspec repo https://github.com/CocoaPods/Specs/tree/master/Specs/f/4/9/Colorful

**Comment by NikKovIos** [comment]
3.0.2 already)

**Comment by Igor-Palaguta** [comment]
Still cannot add 3.0.2 version dependency without specifying git repo

`pod 'Colorful', '3.0.2'`

Output:
```
[!] CocoaPods could not find compatible versions for pod "Colorful":
  In Podfile:
    Colorful (= 3.0.2)

None of your spec sources contain a spec satisfying the dependency: `Colorful (= 3.0.2)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Works only with git

`pod 'Colorful', :git => 'https://github.com/hayashi311/Color-Picker-for-iOS', :tag => '3.0.2'`
